version: "3"
services:
    mongodb:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        command:
            - mongod
        volumes:
            - mongo:/data/db
    sweet:
        build: .
        environment:
            - SECRET=__hZy__TqL__
            - MODE=production
        ports:
            - 8888:8888
        links:
            - mongodb
        depends_on:
            - mongodb
        restart: always
        command:
            - start
        volumes:
            - sweet:/var/sweet
    redis:
        image: redis
        stdin_open: true
        tty: true
volumes:
    mongo:
    sweet: